import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Created by - {' '}
          <code className={styles.techbeast}><a href="https://www.youtube.com/channel/UCAHAG1lCTwj9L2E_ZjOK-8A">Techbeast69</a></code>
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/techbeast69" className={styles.card}>
            <h2>Github</h2>
            <p>Find in-depth information about projects.</p>
          </a>

          <a href="https://instagram.com/techbeast69" className={styles.card}>
            <h2>Instagram</h2>
            <p>Enjoy your programmig journey by sharing some information to public</p>
          </a>

          <a
            href="https://www.youtube.com/channel/UCAHAG1lCTwj9L2E_ZjOK-8A"
            className={styles.card}
          >
            <h2>Youtube</h2>
            <p>Daily Shorts on js projects and other programming related stuff.</p>
          </a>

          <a
            href="https://twitter.com/techbeast69"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Twitter </h2>
            <p>
              Get latest tweets related to JavaScript and TypeScript on Twitter.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          
        >
          Powered by{' '}
          <span className={styles.logo}>
          </span>
          <span className={styles.txtEdit} > Ankit Ojha</span> 
        </a>
      </footer>
    </div>
  )
}
